matrix_id = "k4_m32_ar_hd_sweep_p"
solver = "pulp"
solver_gap = 0.05
solver_time_limit = 120

program_config = "config/program.toml"
message_sizes_mib = [32]  # in MB
algorithms = "ar_having-doubling"

[topology]
k = 4
p = [4, 8, 16, 32, 64, 128, 256, 512]
B = 25  # bytes/ms (50 GBps)
T_reconf = 0.2
T_lat = 0.02

[output]
config_dir  = "logs/generated_configs/k4_m32_ar_hd_sweep_p"
results_csv = "logs/matrix_results-k4_m32_ar_hd_sweep_p.csv"